### ISSUE TITLE
Komorebi Menu Doesn't Show On Desktop

### ISSUE THREAD

**Issue by projectintel-anon** [cheesecakeufo/komorebi#249]
Not sure if this is reported at all, but when installing Komorebi on Ubuntu Budgie 20.10 Groovy Gorilla, right clicking on the Desktop and clicking "change wallpaper" doesn't open Komorebi... it opens GNOME settings instead and goes to the default change wallpaper menu. 

Configuration:

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

AMD A9 APU with RADEON R5 iGPU if needed. Screenshot below shows that Komorebi is indeed running!
![Screenshot from 2020-12-18 01-08-41](https://user-images.githubusercontent.com/55900441/102561850-a1aee880-40cd-11eb-8db5-927bbf1148bc.png)

**Comment by projectintel-anon** [comment]
After more digging, I found that if I switched to standard Ubuntu as my display manager before logging into Ubuntu for the first time, Komorebi works when changing wallpaper... kind of, except the colors are messed up (they are all orange and red) and are super laggy.

**Comment by Ev1lbl0w** [comment]
About the all "orange and red" colors, that's probably these issues: cheesecakeufo#149 and komorebi-fork#50. If it is, there's a proposed workaround at #149, it might work, but if it doesn't, so far the only solution is to uninstall the VAAPI driver.

About the option opening GNOME settings, that's quite odd; could you try our [fork version](https://github.com/Komorebi-Fork/komorebi/releases/tag/v2.2.1), to see if it still happens on that one?

**Comment by projectintel-anon** [comment]
I found an even weirder issue. Logged in this morning, and I have 2 monitors - one laptop screen at 1366x768 and a 1920x1080 monitor on HDMI. I used the following command to make the monitor 60Hz:

`xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync && xrandr --addmode HDMI-A-0 1920x1080_60.00`

And this is what happened:

![Screenshot from 2020-12-18 12-19-31](https://user-images.githubusercontent.com/55900441/102614130-95597880-412b-11eb-8227-513b2b3329b9.png)

My 1366x768 (not on the screenshot) uses GNOME for background, and in the screenshot you can see my 1920x1080 monitor was split into a 1366x768 (which uses Komorebi to change wallpaper correctly) and then a weird distorted border... wtf?

**Comment by projectintel-anon** [comment]
![Screenshot from 2020-12-18 12-23-33](https://user-images.githubusercontent.com/55900441/102614284-dc476e00-412b-11eb-973f-22935b0573fb.png)

Also here is what I meant by the orange and red weirdness - also highlights the weird bordering.

**Comment by Ev1lbl0w** [comment]
Ahh, I think I understand what's happening; in this version, for some reason, Komorebi modifies some GNOME shell settings, changing it's wallpaper to the same one as Komorebi, and hiding it's desktop icons. Even though you're seeing the wallpaper from Komorebi, it is actually not running.

For restoring your desktop icons when you quit Komorebi, try running this:
`gsettings set org.gnome.desktop.background show-desktop-icons true`
*(the fork still removes them, so that needs to be fixed too, thanks for bringing that up :slightly_smiling_face: )*

On the topic of screens, what is your main screen? If it's the right 1366x768 one, then that means you have an external screen to the left, right? Maybe the code is assuming external monitors on the right, will have to check that.

Also do bear in mind there's currently an unfixed crash (Komorebi-fork#18) that will probably happen if you run Komorebi on various screens.

**Comment by projectintel-anon** [comment]
Yeah you are correct. My main screen is the 1366x768 laptop screen on the right, and the second external screen is the huge 1920x1080 one to the left. I did see that thread about crashing with multiple screens before, but figured I might try it regardless.

I also popped in the command to a terminal, it did nothing..
